# Generated by Django 4.2.6 on 2023-11-16 11:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gorynych_app', '0004_usergame'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usergame',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
